config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events
  get "/confirmation_creation" => "events#confirmation_creation"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :events
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
     before_action :find_event, only: [:show, :edit, :update, :destroy, :confirmation_creation]

     def index
       @events = Event.all
     end

    def show
    end

     def new
       @event= Event.new
     end

     def create
       @event = Event.new(event_params)
       @event.user = current_user
       if @event.save
         redirect_to confirmation_creation_path(id: @event.id)
       else
         render :new
       end
     end

     def edit
     end

     def update
       if (@event.user == current_user) && @event.update(event_params)
           #attention le update ci-dessus est le update de active record, pas la méthode update du controleur
         redirect_to confirmation_creation_path(id: @event.id)
       else
         render :edit
       end
     end

     def destroy
       if @event.user == current_user
         @event.destroy
         redirect_to events_path(user_id: current_user.id)
       else
         flash[:alert] = "You can't delete this product"
       end
     end

     def confirmation_creation
     end

     def research
      if params[:event]
         @events = event.select{|event| (event.brand.downcase == params[:event][:brand].downcase)}
       else
         @events =[]
       end
     end

     private
     def event_params
       params.require(:event).permit(:name, :date, :address, :description)
     end

     def find_event
       @event = Event.find(params[:id].to_i)
     end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :name, placeholder: "My birthday party", error: 'Event name is mandatory, please specify one' %>
  <%= f.input :address, placeholder: "133 avenue du Faubourg Saint-Honoré", label:"Address" %>
  <%= f.input :date, label:"date" %>
  <%= f.input :description, placeholder: "No flowers please !", label:"Description" %>
  <%= f.button :submit, "Submit", class: "btn btn-primary" %>
<% end %>

app/views/events/_listing.html.erb
<% @events.each do |event| %>
  <%= link_to event_path (event) do %>
    <div class="card">
      <div class="card-category">Popular</div>
      <div class="card-description">
        <h3><%= event.name %></h2>
        <p>address : <i><%=event.address %></p>
      </div>
    </div>
  <%end %>
<% end %>

app/views/events/confirmation_creation.html.erb
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1 class="text-center">
        Your new event for has been successfully uploaded !
      </h1>
      <ul>
        <li>
          <p>type: <%= @event.address %></p>
        </li>
        <li>
          <p>address: <%= @event.address %></p>
      </ul>
      <p class="text-center">
        <%= link_to "View event Description", event_path(@event), class: "btn btn-success" %>
      </p>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h1 class="text-center">
      Modify the event
    </h1>
    <%= render "form" %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
 <h2>voici la liste des evenements</h2>
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= render "listing" %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div id="map" style="width: 100%; height: 400px;">
      </div>
    </div>
  </div>


</div>

app/views/events/new.html.erb
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h1 class="text-center">
      Create a new event
    </h1>

    <%= render "form" %>


    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="padded">
  </div>

  <div class="media-aside">
    <div class="row">

      <div class="media-section col-xs-12 col-sm-6">
        <h1><%= @event.name%></h1>
        <h5> Last update : <%= @event.updated_at %> </h5>
        <h6> address: <%= @event.address %></h6>
        <% if @event.user == current_user %>
          <%= link_to "Modify", edit_event_path, class: "btn btn-warning" %>
          <%= link_to "Delete", event_path(@event), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-6">

        <div id="map" style="width: 100%; height: 400px;">
        </div>

      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>Welcome to Connexion !</h1>
    <p>Le réseau social d'entreprise de référence</p>
    <%= link_to "SIGN-UP", new_user_registration_path, class:"btn btn-primary btn-lg" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_event_path do %>
                <i class="fa fa-upload"></i>  <%= t(".profile", default: "create an event") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <% if user_signed_in? %>
      <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>